### ISSUE TITLE
Update controller image to be based on Fedora 38

### ISSUE THREAD

**Issue by k-rister** [perftool-incubator/crucible#286]

**Comment by k-rister** [comment]
At this point in time this cannot be done.  There is currently an incompatability between a module being installed via pip and the version of python in Fedora 37:

```
[ERROR] ################################################################################
[ERROR] COMMAND:         /usr/bin/python3 -m pip install ntfy[pid,emoji,xmpp,telegram,instapush,slack,rocketchat] 2>&1
[ERROR] RETURN CODE:     1
[ERROR] COMMAND OUTPUT:
[ERROR]
[ERROR] Requirement already satisfied: ntfy[emoji,instapush,pid,rocketchat,slack,telegram,xmpp] in /usr/local/lib/python3.11/site-packages (2.7.0)
[ERROR] Requirement already satisfied: requests in /usr/lib/python3.11/site-packages (from ntfy[emoji,instapush,pid,rocketchat,slack,telegram,xmpp]) (2.28.1)
[ERROR] Requirement already satisfied: ruamel.yaml in /usr/local/lib/python3.11/site-packages (from ntfy[emoji,instapush,pid,rocketchat,slack,telegram,xmpp]) (0.17.21)
[ERROR] Requirement already satisfied: appdirs in /usr/lib/python3.11/site-packages (from ntfy[emoji,instapush,pid,rocketchat,slack,telegram,xmpp]) (1.4.4)
[ERROR] Collecting emoji
[ERROR]   Downloading emoji-2.2.0.tar.gz (240 kB)
[ERROR]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.9/240.9 kB 3.7 MB/s eta 0:00:00
[ERROR]   Preparing metadata (setup.py): started
[ERROR]   Preparing metadata (setup.py): finished with status 'done'
[ERROR] Collecting instapush
[ERROR]   Downloading instapush-0.1.2.tar.gz (1.7 kB)
[ERROR]   Preparing metadata (setup.py): started
[ERROR]   Preparing metadata (setup.py): finished with status 'done'
[ERROR] Collecting psutil
[ERROR]   Downloading psutil-5.9.4-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (280 kB)
[ERROR]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 280.2/280.2 kB 8.9 MB/s eta 0:00:00
[ERROR] Collecting rocketchat-API
[ERROR]   Downloading rocketchat_API-1.28.1-py3-none-any.whl (20 kB)
[ERROR] Collecting slacker
[ERROR]   Downloading slacker-0.14.0.tar.gz (10 kB)
[ERROR]   Preparing metadata (setup.py): started
[ERROR]   Preparing metadata (setup.py): finished with status 'done'
[ERROR] Collecting telegram-send
[ERROR]   Downloading telegram_send-0.34-py3-none-any.whl (25 kB)
[ERROR] Collecting sleekxmpp
[ERROR]   Downloading sleekxmpp-1.3.3.tar.gz (845 kB)
[ERROR]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 845.0/845.0 kB 14.9 MB/s eta 0:00:00
[ERROR]   Preparing metadata (setup.py): started
[ERROR]   Preparing metadata (setup.py): finished with status 'error'
[ERROR]   error: subprocess-exited-with-error
[ERROR]
[ERROR]   × python setup.py egg_info did not run successfully.
[ERROR]   │ exit code: 1
[ERROR]   ╰─> [21 lines of output]
[ERROR]       Traceback (most recent call last):
[ERROR]         File "<string>", line 2, in <module>
[ERROR]         File "<pip-setuptools-caller>", line 34, in <module>
[ERROR]         File "/tmp/pip-install-zy2m7mek/sleekxmpp_4532f5799c624b3ebe48055ccdc48e06/setup.py", line 19, in <module>
[ERROR]           from sleekxmpp.version import __version__
[ERROR]         File "/tmp/pip-install-zy2m7mek/sleekxmpp_4532f5799c624b3ebe48055ccdc48e06/sleekxmpp/__init__.py", line 20, in <module>
[ERROR]           from sleekxmpp.stanza import Message, Presence, Iq
[ERROR]         File "/tmp/pip-install-zy2m7mek/sleekxmpp_4532f5799c624b3ebe48055ccdc48e06/sleekxmpp/stanza/__init__.py", line 10, in <module>
[ERROR]           from sleekxmpp.stanza.error import Error
[ERROR]         File "/tmp/pip-install-zy2m7mek/sleekxmpp_4532f5799c624b3ebe48055ccdc48e06/sleekxmpp/stanza/error.py", line 9, in <module>
[ERROR]           from sleekxmpp.xmlstream import ElementBase, ET
[ERROR]         File "/tmp/pip-install-zy2m7mek/sleekxmpp_4532f5799c624b3ebe48055ccdc48e06/sleekxmpp/xmlstream/__init__.py", line 9, in <module>
[ERROR]           from sleekxmpp.jid import JID
[ERROR]         File "/tmp/pip-install-zy2m7mek/sleekxmpp_4532f5799c624b3ebe48055ccdc48e06/sleekxmpp/jid.py", line 25, in <module>
[ERROR]           from sleekxmpp.thirdparty import OrderedDict
[ERROR]         File "/tmp/pip-install-zy2m7mek/sleekxmpp_4532f5799c624b3ebe48055ccdc48e06/sleekxmpp/thirdparty/__init__.py", line 13, in <module>
[ERROR]           from sleekxmpp.thirdparty.orderedset import OrderedSet
[ERROR]         File "/tmp/pip-install-zy2m7mek/sleekxmpp_4532f5799c624b3ebe48055ccdc48e06/sleekxmpp/thirdparty/orderedset.py", line 25, in <module>
[ERROR]           class OrderedSet(collections.MutableSet):
[ERROR]                            ^^^^^^^^^^^^^^^^^^^^^^
[ERROR]       AttributeError: module 'collections' has no attribute 'MutableSet'
[ERROR]       [end of output]
[ERROR]
[ERROR]   note: This error originates from a subprocess, and is likely not a problem with pip.
[ERROR] error: metadata-generation-failed
[ERROR]
[ERROR] × Encountered error while generating package metadata.
[ERROR] ╰─> See above for output.
[ERROR]
[ERROR] note: This is an issue with the package mentioned above, not pip.
[ERROR] hint: See above for details.
[ERROR]
[ERROR] ********************************************************************************
[ERROR] Failed to python3 pip install python3 package 'ntfy[pid,emoji,xmpp,telegram,instapush,slack,rocketchat]'
```

**Comment by k-rister** [comment]
Related: https://stackoverflow.com/questions/74006130/attributeerror-module-collections-has-no-attribute-mutableset

**Comment by k-rister** [comment]
The notification subsyste was removed from Crucible since nobody was using it.  This allowed an upgrade to the current Fedora version, 38, to be completed.
